name: gis_env
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - affine=2.4.0
  - aiohappyeyeballs=2.6.1
  - aiohttp=3.11.18
  - aiosignal=1.3.2
  - anyio=4.9.0
  - appdirs=1.4.4
  - argon2-cffi=23.1.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.3.0
  - astral=3.2
  - asttokens=3.0.0
  - async-lru=2.0.5
  - async-timeout=5.0.1
  - attrs=25.3.0
  - babel=2.17.0
  - beautifulsoup4=4.13.4
  - blas=2.131
  - blas-devel=3.9.0
  - bleach=6.2.0
  - bleach-with-css=6.2.0
  - blosc=1.21.6
  - bokeh=2.4.3
  - boost-cpp=1.78.0
  - bottleneck=1.5.0
  - bqplot=0.12.43
  - branca=0.8.1
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.8.3
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cachetools=5.5.2
  - cairo=1.16.0
  - cartopy=0.24.0
  - certifi=2025.8.3
  - cffi=1.17.1
  - cfitsio=4.2.0
  - cftime=1.6.4
  - charset-normalizer=3.4.2
  - click=8.2.1
  - click-plugins=1.1.1
  - cligj=0.7.2
  - cloudpickle=3.1.1
  - colorama=0.4.6
  - colour=0.1.5
  - comm=0.2.2
  - contextily=1.6.2
  - contourpy=1.3.2
  - cryptography=42.0.2
  - curl=8.1.2
  - cycler=0.12.1
  - cython=3.1.3
  - cytoolz=1.0.1
  - dask=2023.3.0
  - dask-core=2023.3.0
  - debugpy=1.8.14
  - decorator=5.2.1
  - defusedxml=0.7.1
  - distributed=2023.3.0
  - earthengine-api=1.5.15
  - ee_extra=0.0.15
  - eerepr=0.1.2
  - elevation=1.1.3
  - embree3=3.13.5
  - ephem=4.2
  - exceptiongroup=1.3.0
  - executing=2.2.0
  - expat=2.7.0
  - fasteners=0.19
  - ffmpeg=2.8.6
  - ffmpeg-python=0.2.0
  - filelock=3.18.0
  - folium=0.19.6
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.58.0
  - fqdn=1.5.1
  - freetype=2.13.3
  - freexl=1.0.6
  - frozenlist=1.6.0
  - fsspec=2025.7.0
  - future=1.0.0
  - gdown=5.2.0
  - geeadd=0.5.6
  - geemap=0.35.3
  - geocoder=1.38.1
  - geographiclib=2.1
  - geojson=3.2.0
  - geopandas=1.0.1
  - geopandas-base=1.0.1
  - geopy=2.4.1
  - geos=3.11.1
  - geotiff=1.7.1
  - gettext=0.24.1
  - gettext-tools=0.24.1
  - giflib=5.2.2
  - glib=2.78.1
  - glib-tools=2.78.1
  - gmp=6.3.0
  - gnutls=3.8.9
  - google-api-core=2.24.2
  - google-api-python-client=2.169.0
  - google-auth=2.40.2
  - google-auth-httplib2=0.2.0
  - google-cloud-core=2.4.3
  - google-cloud-storage=3.1.0
  - google-crc32c=1.7.1
  - google-resumable-media=2.7.2
  - googleapis-common-protos=1.70.0
  - grpcio=1.59.3
  - h11=0.16.0
  - h2=4.2.0
  - h5netcdf=1.6.4
  - h5py=3.8.0
  - hdf4=4.2.15
  - hdf5=1.12.2
  - hpack=4.1.0
  - httpcore=1.0.9
  - httplib2=0.22.0
  - httpx=0.28.1
  - hyperframe=6.1.0
  - icu=70.1
  - idna=3.10
  - imageio=2.37.0
  - importlib-metadata=8.6.1
  - importlib_resources=6.5.2
  - ipyevents=2.0.2
  - ipyfilechooser=0.6.0
  - ipykernel=6.29.5
  - ipyleaflet=0.19.2
  - ipython=8.36.0
  - ipython_pygments_lexers=1.1.1
  - ipytree=0.2.2
  - ipywidgets=8.1.7
  - isoduration=20.11.0
  - jedi=0.19.2
  - jinja2=3.1.6
  - joblib=1.5.0
  - jpeg=9e
  - jplephem=2.23
  - json-c=0.16
  - json5=0.12.0
  - jsonpointer=3.0.0
  - jsonschema=4.23.0
  - jsonschema-specifications=2025.4.1
  - jsonschema-with-format-nongpl=4.23.0
  - jupyter-lsp=2.2.5
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - jupyter_events=0.12.0
  - jupyter_leaflet=0.19.2
  - jupyter_server=2.16.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.4.2
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.3
  - jupyterlab_widgets=3.0.15
  - kealib=1.5.0
  - keyutils=1.6.1
  - kiwisolver=1.4.7
  - krb5=1.20.1
  - lame=3.100
  - lcms2=2.15
  - ld_impl_linux-64=2.43
  - lerc=4.0.0
  - libabseil=20230802.1
  - libaec=1.1.3
  - libasprintf=0.24.1
  - libasprintf-devel=0.24.1
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcurl=8.1.2
  - libdeflate=1.17
  - libedit=3.1.20250104
  - libev=4.33
  - libexpat=2.7.0
  - libffi=3.4.6
  - libfreetype=2.13.3
  - libfreetype6=2.13.3
  - libgcc=15.1.0
  - libgcc-ng=15.1.0
  - libgdal=3.6.2
  - libgettextpo=0.24.1
  - libgettextpo-devel=0.24.1
  - libgfortran=15.1.0
  - libgfortran-ng=15.1.0
  - libgfortran5=15.1.0
  - libglib=2.78.1
  - libgomp=15.1.0
  - libgrpc=1.59.3
  - libhwloc=2.9.1
  - libiconv=1.18
  - libidn2=2.3.8
  - libkml=1.3.0
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libnetcdf=4.9.1
  - libnghttp2=1.58.0
  - libnsl=2.0.1
  - libopenblas=0.3.29
  - libpng=1.6.47
  - libpq=15.2
  - libprotobuf=4.24.4
  - libre2-11=2023.09.01
  - librttopo=1.1.0
  - libsodium=1.0.18
  - libspatialite=5.0.1
  - libsqlite=3.49.2
  - libssh2=1.11.0
  - libstdcxx=15.1.0
  - libstdcxx-ng=15.1.0
  - libtasn1=4.20.0
  - libtiff=4.5.0
  - libunistring=0.9.10
  - libuuid=2.38.1
  - libwebp-base=1.5.0
  - libxcb=1.13
  - libxml2=2.10.3
  - libzip=1.10.1
  - libzlib=1.3.1
  - llvmlite=0.44.0
  - locket=1.0.0
  - logzero=1.7.0
  - lz4=4.3.3
  - lz4-c=1.9.4
  - mapclassify=2.8.1
  - markupsafe=3.0.2
  - matplotlib-base=3.10.3
  - matplotlib-inline=0.1.7
  - mercantile=1.2.1
  - mgrs=1.5.0
  - minizip=4.0.3
  - mistune=3.1.3
  - msgpack-python=1.1.1
  - multidict=6.4.4
  - munkres=1.1.4
  - narwhals=1.40.0
  - nbclient=0.10.2
  - nbconvert-core=7.16.6
  - nbformat=5.10.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - netcdf4=1.6.3
  - nettle=3.9.1
  - networkx=3.4.2
  - nomkl=1.0
  - notebook-shim=0.2.4
  - nspr=4.36
  - nss=3.111
  - numba=0.61.2
  - numexpr=2.10.2
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openblas=0.3.29
  - openh264=2.6.0
  - openjpeg=2.5.0
  - openssl=3.1.8
  - osmnx=2.0.3
  - osmnx-base=2.0.3
  - overrides=7.7.0
  - p11-kit=0.24.1
  - packaging=25.0
  - pandas=2.2.3
  - pandocfilters=1.5.0
  - parso=0.8.4
  - partd=1.4.2
  - patsy=1.0.1
  - pcre2=10.40
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=9.4.0
  - pip=25.1.1
  - pixman=0.46.0
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.3.8
  - plotly=6.1.1
  - poppler=23.03.0
  - poppler-data=0.4.12
  - postgresql=15.2
  - proj=9.1.1
  - prometheus_client=0.22.0
  - prompt-toolkit=3.0.51
  - propcache=0.3.1
  - proto-plus=1.26.1
  - protobuf=4.24.4
  - psutil=7.0.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pvlib=0.12.0
  - pyasn1=0.6.1
  - pyasn1-modules=0.4.2
  - pycparser=2.22
  - pycrs=1.0.2
  - pygments=2.19.1
  - pyogrio=0.10.0
  - pyopenssl=25.1.0
  - pyparsing=3.2.3
  - pyperclip=1.8.2
  - pyproj=3.5.0
  - pyshp=2.3.1
  - pysocks=1.7.1
  - python=3.10.13
  - python-box=7.3.2
  - python-dateutil=2.9.0.post0
  - python-fastjsonschema=2.21.1
  - python-json-logger=2.0.7
  - python-tzdata=2025.2
  - python_abi=3.10
  - pytz=2025.2
  - pyu2f=0.1.5
  - pyyaml=6.0.2
  - pyzmq=26.2.0
  - qhull=2020.2
  - rasterio=1.4.3
  - ratelim=0.1.6
  - re2=2023.09.01
  - readline=8.2
  - referencing=0.36.2
  - requests=2.32.5
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - richdem=2.3.0
  - rio-vrt=0.3.1
  - rioxarray=0.19.0
  - rpds-py=0.25.1
  - rsa=4.9.1
  - ruamel.yaml=0.18.10
  - ruamel.yaml.clib=0.2.8
  - sankee=0.2.5
  - scikit-learn=1.6.1
  - scipy=1.15.2
  - scooby=0.10.1
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - send2trash=1.8.3
  - setuptools=80.9.0
  - sgp4=2.25
  - shapely=2.0.1
  - six=1.17.0
  - skyfield=1.53
  - snappy=1.2.1
  - sniffio=1.3.1
  - snuggs=1.4.7
  - sortedcontainers=2.4.0
  - soupsieve=2.7
  - sqlite=3.49.2
  - stack_data=0.6.3
  - statsmodels=0.14.4
  - tbb=2021.9.0
  - tbb-devel=2021.9.0
  - tblib=3.1.0
  - terminado=0.18.1
  - threadpoolctl=3.6.0
  - tiledb=2.13.2
  - tinycss2=1.4.0
  - tk=8.6.13
  - toml=0.10.2
  - tomli=2.2.1
  - toolz=1.0.0
  - tornado=6.5
  - tqdm=4.67.1
  - traitlets=5.14.3
  - traittypes=0.2.1
  - types-python-dateutil=2.9.0.20250516
  - typing-extensions=4.13.2
  - typing_extensions=4.13.2
  - typing_utils=0.1.0
  - tzcode=2025b
  - tzdata=2025b
  - unicodedata2=16.0.0
  - uri-template=1.3.0
  - uriparser=0.9.8
  - uritemplate=4.1.1
  - urllib3=2.4.0
  - wcwidth=0.2.13
  - webcolors=24.11.1
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - wheel=0.45.1
  - whitebox=2.3.6
  - whiteboxgui=2.3.0
  - widgetsnbextension=4.0.14
  - x264=1!164.3095
  - xarray=2025.4.0
  - xerces-c=3.2.4
  - xorg-kbproto=1.0.7
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.4
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xorgproto=2024.1
  - xorg-xproto=7.0.31
  - xyzservices=2025.4.0
  - xz=5.8.1
  - xz-gpl-tools=5.8.1
  - xz-tools=5.8.1
  - yaml=0.2.5
  - yarl=1.20.0
  - zeromq=4.3.5
  - zict=3.0.0
  - zipp=3.21.0
  - zlib=1.3.1
  - zstandard=0.23.0
  - zstd=1.5.7
  - pip:
      - horayzon==1.2
      - jupyter==1.1.1
      - jupyter-console==6.6.3
      - notebook==7.4.2
      - scikit-learn-extra==0.3.0
prefix: /root/miniconda3/envs/gis_env
